### ISSUE TITLE
Reproducibility problem

### ISSUE THREAD

**Issue by Philonous** [nejla/docker-images#1]
The images we are getting from docker build are not deterministic but rather depends on whatever version the Ubuntu repositories (or anything else we query, like stack in this case) give us at the time we are performing the build. 

One way this becomes a tangible problem is when we want to modify the Dockerfile (or sources), say, to add another dependency, but then the rest of the image shifts below our feet. 

On the opposite side of the spectrum we may _want_ a new version of the image without changing the sources, but then we have to fight the docker cache and also we have the confusing situation that it is not obvious what the supposed changes in the image on Dockerhub are.

**Comment by Philonous** [comment]
One idea to solve this is by using [Nix][1].
Nix allows you to _pin_ a version set of the packages, then all future builds will use this version set, improving consistency and reproducibility. Updating to a new version just means changing the git commit of the package set. You can also choose an older commit, effectively allowing you to downgrade. Even mixed version sets are supported seamlessly, should that ever be necessary. 

A downside of Nix is the rather arcane syntax of the Nix language. Also, a lot of packages make assumptions about absolute paths on the system. However, Nix, by necessity, doesn't follow the [FHS][2]. Packages installed by Nix are automatically fixed to find their dependencies, but the (relative to e.g. Ubuntu) unusual file structure can lead to occasional hickups, particularly by programs that are brought in from outside the Nix package manager (think pip, npm).

There's a ready-made container with nix [on dockerhub][3]

[1]: https://nixos.org/nix/
[2]: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard
[3]: https://hub.docker.com/r/nixos/nix

**Comment by jonkri** [comment]
This issue has been moved. Closing.
